# Dockerfile für den Container mit dem Datenbank-Microservice
FROM python:3.11

# Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere json_database.py und database.json in das Arbeitsverzeichnis im Container
COPY Project/json_database.py Project/database.json /app/

# Installation der Abhängigkeiten
RUN pip install discord.py
RUN pip install flask
RUN pip install requests

# Befehl zum Ausführen des Microservices
CMD ["python", "json_database.py"]