version: '3.11'

services:
  container1:
    image: itznox/app-service:1.2
    ports:
      - "8000:8000"
    depends_on:
      - container2
    environment:
      - DISCORD_TOKEN=MTI0NzkyNzAxODU3OTAzODI3OA.G6W59m.a6JMkmBHooSvt56u7PNJQRe8R7tLRhWXedpYs0
    networks:
      - server

  container2:
    image: itznox/database-service:1.2
    networks:
      - server

networks:
  server:
    external: true
