# Dockerfile für den Container mit dem App-Microservice
FROM python:3.11

# Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere dungeons.py und main.py in das Arbeitsverzeichnis
COPY Project/dungeons.py /app/

# Installation der Abhängigkeiten
RUN pip install discord.py
RUN pip install requests
RUN pip install flask 

# Befehl zum Ausführen des Microservices
CMD ["python", "dungeons.py"]